## NumPy = Numerical Python
### A library in Python
### Support large and multi-dimensional arrays and matrices
### Allow mathematical operations
### More memory efficient than Python
### specifying the data type (dtype) in NumPy allows for precise control over memory usage and how data is stored and processed

In [14]:
a = [1,2,3,4,5,10]

In [3]:
b=[[1],[2],[3],[5]]

In [15]:
a

[1, 2, 3, 4, 5, 10]

In [5]:
b

[[1], [2], [3], [5]]

In [6]:
import numpy

In [8]:
import numpy as np #Package an alias name np to be used in our code, this is just for user friendliness

In [16]:
arr=np.array(a)

In [17]:
arr.shape

(6,)

In [18]:
type(arr)

numpy.ndarray

numpy.ndarray - is the primary type used by the NumPy library to represent multidimensional arrays, which are also known as n-dimensional arrays. This type is extremely useful for numerical computations, as it provides an efficient way to store and manipulate large sets of data in a structured format.

In [20]:
arr.dtype

dtype('int32')

In [13]:
arr.dtype?

Type:            dtype[int32]
String form:     int32
Length:          0
File:            c:\users\sanja\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
dtype(dtype, align=False, copy=False)

Create a data type object.

A numpy array is homogeneous, and contains elements described by a
dtype object. A dtype object can be constructed from different
combinations of fundamental numeric types.

Parameters
----------
dtype
    Object to be converted to a data type object.
align : bool, optional
    Add padding to the fields to match what a C compiler would output
    for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
    or a comma-separated string. If a struct dtype is being created,
    this also sets a sticky alignment flag ``isalignedstruct``.
copy : bool, optional
    Make a new copy of the data-type object. If ``False``, the result
    may just be a reference to a built-in data-type object.

See also
--------
result_type

In [21]:
import numpy as np

# Creating an array with default data type (usually float64)
arr_default = np.array([1, 2, 3, 4])
print("Default dtype:", arr_default.dtype)  # Output: int64 (or float64, depending on the input)

# Creating an array with int32 dtype
arr_int32 = np.array([1, 2, 3, 4], dtype='int32')
print("Array with dtype 'int32':", arr_int32)
print("Data type of arr_int32:", arr_int32.dtype)  # Output: int32

# Creating an array with float32 dtype
arr_float32 = np.array([1.0, 2.0, 3.0], dtype='float32')
print("Array with dtype 'float32':", arr_float32)
print("Data type of arr_float32:", arr_float32.dtype)  # Output: float32

# Creating an array with complex numbers
arr_complex = np.array([1, 2, 3], dtype='complex')
print("Array with complex dtype:", arr_complex)
print("Data type of arr_complex:", arr_complex.dtype)  # Output: complex128 (default for complex)

Default dtype: int32
Array with dtype 'int32': [1 2 3 4]
Data type of arr_int32: int32
Array with dtype 'float32': [1. 2. 3.]
Data type of arr_float32: float32
Array with complex dtype: [1.+0.j 2.+0.j 3.+0.j]
Data type of arr_complex: complex128


In [22]:
arr_2d = np.array([[1,2,3],[5,6,7]])

In [23]:
arr_2d.shape

(2, 3)

In [24]:
arr_3d = np.array([[[1,2,3],[2,3,4],[4,5,6]],[[4,5,6],[7,8,9],[10,11,12]]])

In [25]:
arr_3d.shape

(2, 3, 3)

In [28]:
arr_sample = np.array(range(0,16))
arr_sample

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
arr_sample = arr_sample.reshape((4,4))

In [30]:
arr_sample.shape

(4, 4)

In [31]:
arr_sample

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
arr2 = arr_sample.T

In [33]:
arr_resultant = arr_sample+arr2

In [34]:
arr_resultant

array([[ 0,  5, 10, 15],
       [ 5, 10, 15, 20],
       [10, 15, 20, 25],
       [15, 20, 25, 30]])

In [35]:
arr_resultant = arr_sample-arr2

In [36]:
arr_resultant

array([[ 0, -3, -6, -9],
       [ 3,  0, -3, -6],
       [ 6,  3,  0, -3],
       [ 9,  6,  3,  0]])

In [37]:
np.add(arr_sample,arr2)

array([[ 0,  5, 10, 15],
       [ 5, 10, 15, 20],
       [10, 15, 20, 25],
       [15, 20, 25, 30]])

In [38]:
np.subtract(arr_sample,arr2)

array([[ 0, -3, -6, -9],
       [ 3,  0, -3, -6],
       [ 6,  3,  0, -3],
       [ 9,  6,  3,  0]])

In [39]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [40]:
np.multiply(a,b)

array([[4, 0],
       [0, 2]])

In [42]:
np.nan?

Type:        float
String form: nan
Docstring:   Convert a string or number to a floating point number, if possible.

In [48]:
np.concatenate([arr_sample,arr2],axis = 1)

array([[ 0,  1,  2,  3,  0,  4,  8, 12],
       [ 4,  5,  6,  7,  1,  5,  9, 13],
       [ 8,  9, 10, 11,  2,  6, 10, 14],
       [12, 13, 14, 15,  3,  7, 11, 15]])

In [44]:
arr_sample

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
arr2

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [49]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [50]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [51]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.sort([1,2,3,10,5])

array([ 1,  2,  3,  5, 10])